import Head from 'next/head'
import Portfoliowrapper from './common/portfoliowrapper'
import About from './home/about'
import Contact from './home/contact'
import Footer from './home/footer'
import Hero from './home/hero'
import Projects from './home/projects'
import Skills from './home/skills'
import style from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='main'>
        <Portfoliowrapper>
          <Hero/>
          <About/>
          <Skills/>
          <Projects/>
          <Contact/>
          <Footer/>
        </Portfoliowrapper>
      </section>
    </>
  )
}
